# Generated by Django 4.0.2 on 2022-05-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_FreshProducts', '0002_alter_magazzino_barcode_alter_magazzino_shop_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='magazzino',
            unique_together={('Barcode', 'Shop_code')},
        ),
    ]
